export const MATERIALS = {
  brickCeramic8: { label: 'Ladrillo cerámico hueco 8 cm', unit: 'u' },
  brickCeramic12: { label: 'Ladrillo cerámico hueco 12 cm', unit: 'u' },
  brickCeramic18: { label: 'Ladrillo cerámico hueco 18 cm', unit: 'u' },
  cement50: { label: 'Cemento 50 kg', unit: 'bolsa' },
  lime25: { label: 'Cal hidratada 25 kg', unit: 'bolsa' },
  sand: { label: 'Arena', unit: 'm³' },
  plasterMortar: { label: 'Mortero para revoque', unit: 'm³' },
  drywallBoard: { label: 'Placa de yeso 1,20 × 2,40 m', unit: 'placa' },
  stud70: { label: 'Montante 70 mm × 3 m', unit: 'u' },
  track70: { label: 'Solera 70 mm × 3 m', unit: 'u' },
  drywallScrew: { label: 'Tornillo para placa', unit: 'u' },
  jointTape: { label: 'Cinta para juntas', unit: 'rollo' },
  jointCompound: { label: 'Masilla para juntas 18 kg', unit: 'balde' },
  insulationRoll: { label: 'Aislación 12 m²', unit: 'rollo' },
  ceilingProfile: { label: 'Perfil cielorraso 3 m', unit: 'u' },
  perimeterProfile: { label: 'Ángulo perimetral 3 m', unit: 'u' },
  hanger: { label: 'Vela / suspensión', unit: 'u' },
  meshRoll: { label: 'Tejido romboidal rollo 10 m', unit: 'rollo' },
  fencePost: { label: 'Poste para cerco', unit: 'u' },
  tensionWire: { label: 'Alambre tensor rollo 100 m', unit: 'rollo' },
  bindingWire: { label: 'Alambre de atar 1 kg', unit: 'kg' },
  concrete: { label: 'Hormigón elaborado / equivalente', unit: 'm³' },
  stone: { label: 'Piedra partida', unit: 'm³' },
  poolBlock: { label: 'Bloque de hormigón 20 × 20 × 40 cm', unit: 'u' },
  waterproof: { label: 'Impermeabilizante cementicio 20 kg', unit: 'bolsa' },
  poolFinish: { label: 'Revestimiento interior de pileta', unit: 'm²' },
  tileAdhesive: { label: 'Adhesivo para revestimiento 25 kg', unit: 'bolsa' },
  grout: { label: 'Pastina 5 kg', unit: 'bolsa' }
};
